/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 Chair.gltf 
*/

import React from 'react'
import { Plane, useGLTF } from '@react-three/drei'
import { MeshStandardMaterial } from 'three';

export default function Model(props) {

  const angleInRadians = (angelInDeg) => {
    return (Math.PI / 180) * angelInDeg;
  }

  const { nodes, materials } = useGLTF('./model/Chair/Chair.gltf')  
  return (
    <group {...props} dispose={null}>
      <group castShadow receiveShadow position={[0, 0.5, 0]} rotation={[0, 1.571, 0]} scale={1.294}>
        <mesh geometry={nodes.Cube006.geometry} material={materials.leather} />
        <mesh geometry={nodes.Cube006_1.geometry} material={materials['wood.001']} />
      </group>
    </group>
  )
}

useGLTF.preload('./model/Chair/Chair.gltf')
