/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 Chair.gltf 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('./model/Chair/Chair.gltf')
  return (
    <group {...props} dispose={null}>

      <group position={[-0.012, 0.33, -0.083]} rotation={[-0.217, 0.006, 0.001]} scale={[5, 5, 5]}>
        <mesh geometry={nodes.Cube015.geometry} material={materials.scheep0} />
        <mesh geometry={nodes.Cube015_1.geometry} material={materials['oak-mod']} />
      </group>
    </group>
  )
}

useGLTF.preload('./model/Chair/Chair.gltf')

// -0.012, 0.33, -0.083
