/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 chair3.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('./model/chair3.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Retopo_Cube003.geometry} material={materials.leather} position={[0, 0.65, 0]} rotation={[0, 1.571, 0]} scale={1.294} />
    </group>
  )
}

useGLTF.preload('./model/chair3.glb')
