/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 Sofa.gltf 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('./model/Sofa/Sofa.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[0, -1, 0]} scale={2.5}>
        <mesh geometry={nodes.Legs.geometry} material={materials['Legs metallic']} position={[-0.01, 0.094, -0.312]} rotation={[Math.PI, 0, Math.PI]} />
        <mesh geometry={nodes.Cusion002.geometry} material={materials['cusion yellow']} position={[-0.866, 0.611, -0.291]} rotation={[2.531, -0.498, 1.21]} scale={[0.39, 0.853, 0.698]} />
        <mesh geometry={nodes.Cusion001.geometry} material={materials['cusion yellow']} position={[-1.088, 0.622, -0.154]} rotation={[1.897, -1.162, -2.842]} scale={[0.388, 0.847, 0.675]} />
        <mesh geometry={nodes.Cusion.geometry} material={materials['cusion yellow']} position={[0.363, 0.608, -0.336]} rotation={[2.728, -0.02, -1.485]} scale={[0.386, 0.853, 0.614]} />
        <mesh geometry={nodes.Sofa.geometry} material={materials['rød brown']} position={[0.028, 0.224, -0.289]} rotation={[0, -Math.PI / 2, 0]} scale={[1, 1, 1.013]} />
      </group>
    </group>
  )
}

useGLTF.preload('./model/Sofa/Sofa.gltf')
